sim:
  type: ofdm_awgn
  seed: 1234
  autoramp: true
tx:
  M: 4
ofdm:
  nfft: 256
  cp: 0.125
  n_subcarriers: 64
  minislot_symbols: 4
channel:
  snr_db_list:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
autoramp:
  target_errs: 100
  min_bits: 20000
  max_bits: 2000000
io:
  write_json: true
  out_json: artifacts/m1_ofdm_awgn_results.json
urllc:
  five_qi: 85
  core_budget_ms: 2.0
  app_payload_bytes: 32
  n_independent_tries: 1
nr:
  mu: 2
  minislot_symbols: 4
  cg_ul:
    period_ms: 1.0
    K: 2
    early_stop: true
  harq:
    enabled: false
    k1_symbols: 0
    k2_symbols: 0
