sim:
  type: ofdm_m2
  seed: 1234
  autoramp: true
tx:
  M: 16
  n_bits: 200000
ofdm:
  nfft: 256
  cp: 0.125
  n_subcarriers: 64
  minislot_symbols: 14
pilots:
  spacing: 2
  offset: 0
  seed: 999
  power_boost_db: 3.0
  power_mode: constrained
channel:
  model: tdl
  snr_db_list:
  - 2.0
  - 4.0
  - 6.0
  - 8.0
  - 12.0
  - 16.0
  seed: 2025
  tdl:
    delays:
    - 0
    - 3
    - 5
    powers_db:
    - 0.0
    - -4.0
    - -8.0
eq:
  type: mmse
autoramp:
  target_errs: 200
  base_min_bits: 200000
  min_used_res: 2000000
  max_bits: 2000000
  noise_blend_weight: 0.0
  min_bits: 100000
  growth: 2.0
io:
  write_json: true
  out_json: artifacts/m2_ofdm_tdlc_autoramp.json
  plot: true
  out_plot: artifacts/m2_ofdm_tdlc_auto_curves.png
  show_plot: false
urllc:
  five_qi: 85
  core_budget_ms: 2.0
  app_payload_bytes: 32
  n_independent_tries: 1
nr:
  mu: 2
  minislot_symbols: 14
  cg_ul:
    period_ms: 1.0
    K: 2
    early_stop: true
  harq:
    enabled: false
    k1_symbols: 0
    k2_symbols: 0
