sim:
   type: ofdm_m2
   seed: 1234

tx:
   M: 4
   n_bits: 240000

ofdm:
   nfft: 256
   cp: 0.125
   n_subcarriers: 64
   minislot_symbols: 14

pilots:
   spacing: 8     # pilot every 4th subcarrier
   offset: 0
   seed: 999
   power_boost_db: 3.0

channel:
   model: tdl
   snr_db_list: [0, 2, 4, 6, 8, 10]
   tdl:
     delays: [0, 3, 5]          # samples (≤ Ncp)
     powers_db: [0.0, -4.0, -8.0]

eq:
   type: mmse   # or mmse

io:
   write_json: true
   out_json: artifacts/m2_ofdm_qpsk_tdlc.json
