sim:
  type: m2_then_bler
  seed: 44
  autoramp: false

tx:
  M: 4

ofdm:
  nfft: 256
  n_subcarriers: 120
  cp: 0.125
  minislot_symbols: 7

# Optional, explicit numerology block (your code also reads nr/ofdm if this is absent)
numerology:
  mu: 2
  L_symbols: 7
  cp_fraction: 0.125

nr:
  mu: 2
  minislot_symbols: 7
  dmrs:
    freq_density: 3
    offset_sc: 0
    seed: 2025
    power_boost_db: 3.0
    power_mode: budgeted
  cg_ul:
    period_ms: 1.0
    K: 2
    early_stop: true
  harq:
    enabled: false   # BLER path prefers urllc.harq below

pilots:
  spacing: 2
  offset: 0
  seed: 2025
  power_boost_db: 3.0
  power_mode: budgeted

channel:
  model: tdl
  snr_db_list:
    - -2
    - 0
    - 2
    - 4
    - 6
    - 8
    - 12
    - 16
    - 18
    - 20
    - 22
    - 24
  tdl:
    delays: [0, 2, 4, 6]
    powers_db: [0.0, -2.5, -5.5, -9.0]

urllc:
  five_qi: 86
  app_payload_bytes: 32
  core_budget_ms: 2.0
  tb_payload_bytes: 48
  # Timely BLER settings used by the BLER loop
  deadline_ms: 8.0
  harq:
    enabled: true
    max_retx: 1            # total attempts = 2 (1 retransmission)
    combining: chase
    stop_on_first_crc_pass: true

fec:
  # none | repeat | ldpc_syst | ldpc_qc
  type: ldpc_syst
  rate: 0.5
  seed: 2025
  density: 0.05
  max_iters: 40
  qc:
    use_builtin_bg2_tiny: true   # set false + base_graph_path to use a real NR BG later
    # base_graph_path: path/to/bg.json
    lifting_Z: 32

bler:
  packets_per_snr: 2000
  min_errors: 50

io:
  write_json: true
  plot: true
  show_plot: false
  m2:
    out_json: artifacts/m2_then_bler/m2_curves.json
    out_plot: artifacts/m2_then_bler/m2_curves.png
  bler:
    out_json: artifacts/m2_then_bler/bler_vs_snr.json
    out_plot: artifacts/m2_then_bler/bler_vs_snr.png
  out_urllc_json: artifacts/urllc_budget.json
