# configs/ofdm_awgn_qpsk.yaml

sim:
  type: ofdm_awgn
  seed: 1234
  autoramp: true        # turn on autoramp sweep

tx:
  M: 4                  # QPSK

ofdm:
  nfft: 256
  cp: 0.125
  n_subcarriers: 64
  minislot_symbols: 4   # {2,4,7} typical for M1

channel:
  snr_db_list: [0, 2, 4, 6, 8, 10]

autoramp:
  target_errs: 100
  min_bits: 20000
  max_bits: 2000000


io:
  write_json: true
  out_json: artifacts/ofdm_qpsk_result.json
